format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/accessom2_restart.nml
  hashes:
    binhash: 2fc89a97276f7fc13b71aafcd78d326c
    md5: c11bbb845bc40b7e9ac9788b3af7e74c
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ice/grid.nc
  hashes:
    binhash: 18d86e2a87d68e7fe68935508d1b1acd
    md5: 24920ffb6c0fea5f6ec1e590a5f46280
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ice/i2o.nc
  hashes:
    binhash: 950d467bac0ff9ad5dd196c9f2352f48
    md5: fbc9d8bb85093a809116752767e4dc2c
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ice/ice.restart_file
  hashes:
    binhash: 8e6c704cc96b2e85747aa3da4b9fc05a
    md5: 372f5e0c420560bccf1166d3d2c3fdfa
work/ice/RESTART/iced.2063-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ice/iced.2063-01-01-00000.nc
  hashes:
    binhash: 94ffc59b4d73573c2d5f2c1cc94dc4e1
    md5: 051fa56df7f8d938590d95aa7a11271b
work/ice/RESTART/iced.2064-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ice/iced.2064-01-01-00000.nc
  hashes:
    binhash: 4b2cb594a53399a447fa4a85045de46b
    md5: 4234f5435e05f31ee40a5b6a50381abc
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ice/kmt.nc
  hashes:
    binhash: 2c3e23857dcd46d9b2404d9621d0ad1e
    md5: 73d65aaee8da5caa8786963866ddc375
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ice/mice.nc
  hashes:
    binhash: 04eb443204f9d1d843b0e58efb1d95fe
    md5: 81bb9d4ce5524952e10a4233ad1ce912
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ice/monthly_sstsss.nc
  hashes:
    binhash: 707d79eae1b14f440b4c5ecc5453809c
    md5: 598c7aa8a08fe3f48a621f781dd26331
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ice/o2i.nc
  hashes:
    binhash: 2cb9187d8e7cf1ba37ac56d312dbd85e
    md5: e05eb21d7890c019f59f5c303cef2e0c
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ice/sicemass.nc
  hashes:
    binhash: 8d4baf59b92e29ecad1470291830a801
    md5: 3066d7b29e704dbaf44a3cff6b3cfe40
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ice/u_star.nc
  hashes:
    binhash: 727066ff47ef0d7242e428cc45598f02
    md5: af8dc99d2c1af33692e54112d13607d1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ocean/ocean_age.res.nc
  hashes:
    binhash: 34d39d09c6b8ae8deea714d1b4201996
    md5: 14764b21a69056e76ce27c2102ab4708
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4947c59ef02a7539a08e4f252447d1c1
    md5: dcaf403a47a3aeac2d91142e0069482d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2d8dc11c3a6385ededcd2e25c5449f29
    md5: 24e0bc6f2a690647c156ba449f45d3a7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ocean/ocean_density.res.nc
  hashes:
    binhash: 5d4512297c3b808355f00003de5eacae
    md5: d4632849b607d17f1d62e9bbf838e66e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f3bd5f38225947886e8b514f8e7b2e5b
    md5: 875c1822b39614c837c71721df634a92
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 72b37df7e52ea2807199f16a07a88834
    md5: 8184f617a9c1080f5340b33ed4ada1c2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6b39778b90294c6ae7259e8ccd0e10bd
    md5: 4d9056c0aa081e54bd5607be66aa4b21
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ocean/ocean_solo.res
  hashes:
    binhash: 94f5cffdfb6c000e755ca119cac684e8
    md5: 65dd386a021e3d04468dbe42cb0ded18
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6ac55c4531c45e43efcef88b2cbfdee8
    md5: 8d043b19b58e334f29669c7ef6196821
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 53bc3a0e3b2936b01f30a87913954dfc
    md5: cb08cdb46d53a40b19078bcd827f2105
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ocean/ocean_tracer.res
  hashes:
    binhash: cc5a6ce727bafb719a591d93f20b33c6
    md5: ae7ed1d8f9a5b58805abaede023fc9e0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5292b584535ea7bfcbd03dc574058d2b
    md5: 1390ab40abc0a0a024ad3c8f1f187bb7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_norediGM/restart081/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c7712e5eaf492f0990ab0de5239a630a
    md5: 843f711666052c381bd4334c5c198457
